# Generated by Django 2.1 on 2022-10-01 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.TextField()),
                ('monthly_price', models.IntegerField()),
                ('yearly_price', models.IntegerField()),
                ('video_quality', models.TextField()),
                ('resolution', models.TextField()),
                ('ph', models.IntegerField()),
                ('tab', models.IntegerField()),
                ('comp', models.IntegerField()),
                ('tv', models.IntegerField()),
                ('no_active', models.IntegerField()),
            ],
        ),
    ]
